### ISSUE TITLE
验证成功后获取不到车辆数据

### ISSUE THREAD

**Issue by kriskwok** [georgezhao2010/fordpass_china#11]
Logger: homeassistant.config_entries
Source: custom_components/fordpass_china/__init__.py:77
Integration: FordPass China ([documentation](https://github.com/georgezhao2010/fordpass_china), [issues](https://github.com/georgezhao2010/fordpass_china/issues))
First occurred: 23:17:53 (1 occurrences)
Last logged: 23:17:53

Error unloading entry 13********95@林肯之道 for fordpass_china
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/fordpass_china/__init__.py", line 77, in async_unload_entry
    del hass.data[config_entry.entry_id]
KeyError: 'eb5a92de2fb31e60960d1694e28d4989'

**Comment by kriskwok** [comment]
之前一直可以用，今天换了token就获取不到车辆数据了，麻烦大神帮忙看看 @georgezhao2010 
<img width="276" alt="image" src="https://github.com/georgezhao2010/fordpass_china/assets/31760242/acf636ed-b895-497c-b57e-a6ee72223b90">

**Comment by kriskwok** [comment]
补充下日志
<img width="830" alt="image" src="https://github.com/georgezhao2010/fordpass_china/assets/31760242/3d65ddea-3d3e-4e22-9522-51e8d66a755d">

**Comment by georgezhao2010** [comment]
车辆信息获取接口已变动，还没时间去搞他
